dist: xenial

addons:
  snaps:
    - name: hugo
    - name: aws-cli
      classic: true
      channel: latest/edge

before_script:
  - rm -rf public 2> /dev/null

script:
  - hugo
  - mkdir -p final_output/work/
  - cp -r public/* final_output/work/
  - cp -r resume/* final_output/

before_deploy:
  - ./aws_creds_env.sh

deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET
  bucket: "sharmamohit.com"
  skip_cleanup: true
  acl: public_read
  local_dir: final_output

after_deploy:
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
