dist: focal

addons:
  apt:
    update: true

before_script:
  - rm -rf work/public 2> /dev/null
  - rm -rf work/final_output 2> /dev/null
  - sudo apt-get install hugo

script:
  - hugo -s work
  - mkdir -p work/final_output/work/
  - cp -r work/public/* work/final_output/work/
  - cp -r landing_page/* work/final_output/

before_deploy:
  - ./aws_creds_env.sh
  - sudo apt-get install -y awscli

deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET
  bucket: "sharmamohit.com"
  skip_cleanup: true
  acl: public_read
  local_dir: final_output

after_deploy:
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
